// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFUZV4F0TDUJkgN8cWEBWBeQN64re_LUA',
    appId: '1:899897731776:web:a8c842dc99b213e34f9b25',
    messagingSenderId: '899897731776',
    projectId: 'testing-26a69',
    authDomain: 'testing-26a69.firebaseapp.com',
    storageBucket: 'testing-26a69.appspot.com',
    measurementId: 'G-18MJ67387B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAenXrBugkrpbKDSWN8ylXIXkdMsLRTNsA',
    appId: '1:899897731776:android:5724db5caab0c3eb4f9b25',
    messagingSenderId: '899897731776',
    projectId: 'testing-26a69',
    storageBucket: 'testing-26a69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz-Km1qhBOXEwIqGH7m7XdHh1IaySkRJs',
    appId: '1:899897731776:ios:6af021616fd5cd774f9b25',
    messagingSenderId: '899897731776',
    projectId: 'testing-26a69',
    storageBucket: 'testing-26a69.appspot.com',
    iosClientId: '899897731776-8citturkm0ekhqbcas7662f4psmo4ho1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFUZV4F0TDUJkgN8cWEBWBeQN64re_LUA',
    appId: '1:899897731776:web:11b1874479dba94b4f9b25',
    messagingSenderId: '899897731776',
    projectId: 'testing-26a69',
    authDomain: 'testing-26a69.firebaseapp.com',
    storageBucket: 'testing-26a69.appspot.com',
    measurementId: 'G-3SP2KS12DK',
  );
}
